# H2 DB Configuration (persistent)
spring.datasource.url=jdbc:h2:file:./data/schedulingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Enable H2 console (for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL logs in console (optional)
spring.jpa.show-sql=true
